### ISSUE TITLE
feature request: hide on lose focus

### ISSUE THREAD

**Issue by z-huabao** [bigbn/drop-down-terminal-x#16]
[hide on lose focus](https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/60)
or 
normally, terminal will close after pressed shotcut when terminal showing but lose fucus
I want it can refocus into terminal !

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/59631256-70600000-9158-11e9-8d55-c8ba9d1f0a73.png)
