### ISSUE TITLE
Drop-down-terminal-x hijacks the ~ key

### ISSUE THREAD

**Issue by pseudo-morph** [bigbn/drop-down-terminal-x#22]
In it's default setting on Ubuntu 18.10, drop-down-terminal-x hijacks the ~ key. This means when it's enabled its impossible to type a ~ both in the application and anywhere else.

Action: Press shift `
Expected result: ~
Actual result: [nothing]

Steps to reproduce:
Enable drop-down-terminal-x
Press ` to open terminal 
Press shift ` (to type ~)
Press ` to close terminal
Click in any other text entry field
Press shift ` (to type ~)

**Comment by bigbn** [comment]
This is default mainstream (gnome-shell, mutter) behaviour. Right now I see no ways to change it in extension. 

    global.display.add_keybinding 

has no any flags to regulate this issue.
You can check it by setting this key in gnome settings for any standard action, the behavior will be the same.

**Comment by pseudo-morph** [comment]
Ah, that's a shame, tilde is pretty important for navigating the command line. I guess the simple solution is to use a different shortcut key.

**Comment by mmrezaie** [comment]
On Fedora (30) for some reason I do not have this problem. But on Ubuntu (18.10) I have. Not sure if it is a relevant info.

**Comment by kamleshkarwande** [comment]
As of now using another shortcut key "Alt + ~"
