### ISSUE TITLE
Allow transparent background color

### ISSUE THREAD

**Issue by amivaleo** [bigbn/drop-down-terminal-x#25]
Hi!

I much appreciate your extension. It's part of my daily worflow.
Still, I would like to have some more option.
One of these is: transparent background.

Can you please let the use decide the level of transparency of the terminal background? There should be some standard gtk widget for that, so I hope it won't require too much effort.

Thank you again for this jewel/software. :)

**Comment by bigbn** [comment]
Hello. Transparency option already exist:

![image](https://user-images.githubusercontent.com/740864/54867330-8730c980-4d98-11e9-8bf1-088909abd06f.png)
![image](https://user-images.githubusercontent.com/740864/54867335-93b52200-4d98-11e9-90bb-378604dd6afa.png)

**Comment by amivaleo** [comment]
Yes, yes, yes...
Sorry.
I found that only a few minutes after posting here.
Sorry...!
