### ISSUE TITLE
Terminal doesn't get focused (again)

### ISSUE THREAD

**Issue by jelmerf** [bigbn/drop-down-terminal-x#32]
On current master and my system (ubuntu 18.04 on Xorg) the terminal doesn't get focused; even though under some conditions the cursor appears as if focused. Clicking the terminal makes it receive focus correctly.

**Comment by ericdallo** [comment]
+1 on Debian 10

**Comment by aytugana** [comment]
+1 ubuntu 18.04 gnome-shell 3.28.4

**Comment by bigbn** [comment]
Does it still an issue even after reboot?

**Comment by lukas-runge** [comment]
+1 ubuntu 18.04 gnome-shell 3.28.4
Clean Ubuntu 18.04 Install
Persists after reboot... Please fix - other than that bug your Extension is awesome!
Thanks for your great work so far!

**Comment by bigbn** [comment]
Closed by mistake, reopened

**Comment by kamleshkarwande** [comment]
Hi Guys, A very useful utility. Saves tonnes of time and stress.
Can you please update on the issue or let us know any settings/tweak for the same?

**Comment by bigbn** [comment]
@kamleshkarwande, sorry but there is no reason/solution found yet, I'l try to fix it as soon as possible

**Comment by bigbn** [comment]
Commit 7dd85dd84a836ed12d91c8980a7e9f8b8e46ef66 may solve the issue. Could somebody to check it?

**Comment by lukas-runge** [comment]
Sadly not for me at least. I still get the exact same behaviour as before. Maybe the issue has to do something with the changes made on 7. Jul #30 
The original repo your project is forked from works fine btw.
Thanks for your work @bigbn and good luck finding the bug!

**Comment by bigbn** [comment]
> Sadly not for me at least. I still get the exact same behaviour as before. Maybe the issue has to do something with the changes made on 7. Jul #30
> The original repo your project is forked from works fine btw.
> Thanks for your work @bigbn and good luck finding the bug!

Just checked this on fresh ubuntu ubuntu-18.04.3-desktop-amd64. After installing from extensions.gnome.org I've got no focus. But changing line from previous commit and reboot make focus work as expected.

**Comment by lukas-runge** [comment]
Sorry @bigbn - you are right! Just tried completely removing and manually reinstalling the extension and it worked. Only issue that persists now then is, that the terminal does not get focussed when it's first opened after reboot or install. For me there's another issue with the "Hide on focus out" and "Hide on escape" options. They make gnome crash for me. (Should I open Issues for those things here on Github?) Other than that the focus thing seems to work now. Thank you very much!

**Comment by bigbn** [comment]
@lukas-runge hope this d659205ea5125e1966bbfe9bb40f81fe5837496e helps

**Comment by lukas-runge** [comment]
@bigbn yeah it sure helped - gnome is not crashing anymore. Hide on escape seems to work flawlessly now. Hide on focus out still has a weird behaviour. I can't close the terminal anymore when it is activated. It seems to automatically reopen instantly again. Thank you very much for those fast improvements/fixes - you rock!

**Comment by kamleshkarwande** [comment]
Now it's WORKING....

I tried the manual.
First removed the previously installed extension. then followed these steps.

$ git clone https://github.com/bigbn/gs-extensions-drop-down-terminal.git /tmp/drop-down-terminal
$ cp -R /tmp/drop-down-terminal/drop-down-terminal-x@bigbn.pro ~/.local/share/gnome-shell/extensions/

GNOME Shell 3.28.4
Ubuntu 18.04 (not a clean install)

And now it's working. thanks for the quick help.
