### ISSUE TITLE
Feature Request: Customizable Cursor Shape

### ISSUE THREAD

**Issue by iranvir** [bigbn/drop-down-terminal-x#34]
Currently, the drop down terminal only supports block style cursor. Personally, I like I beam cursors, and I understand that other users might have other perferences.

I would really love to have (and even help create!) an option to customize cursor shape. At least have the three most common variants available, i.e, Block, I beam and Underscore.

Let me know if there's anything I can do to help you with this (testing, implementation ,etc) and thank you for this wonderful project,

**Comment by bigbn** [comment]
This feauture has been already implemented before I've made this fork
![image](https://user-images.githubusercontent.com/740864/61576302-9545eb00-aae9-11e9-9474-1a46f4fd3107.png)

**Comment by iranvir** [comment]
Sorry, I am dumb :weary:
