### ISSUE TITLE
Feature request: Place tabs on top

### ISSUE THREAD

**Issue by ghost** [bigbn/drop-down-terminal-x#35]
Is it possible to put the tabs bar on top? my shell starts from bottom always, and putting the tabs bar on top gets them out of (immediate) sight.

**Comment by bigbn** [comment]
Yes. I'm able to implement it. Will do it as soon as get free time for it

**Comment by ghost** [comment]
many thanks, really appreciate it.

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/64123981-e0c10980-cdb6-11e9-9b61-cf694d5fef6e.png)
