### ISSUE TITLE
White border/trim around terminal even with 0px padding

### ISSUE THREAD

**Issue by amankhoza** [bigbn/drop-down-terminal-x#36]
Would be nice if this border isn't visible at all or if you can hide it when padding is set to 0px.

**Comment by amankhoza** [comment]
Similar to #28, gap is gone now but white trim remains.

**Comment by daleosm** [comment]
This is still occurring on Pop_OS! with both the current git and gnome extensions channels. I will fix it myself and post it.

**Comment by bigbn** [comment]
Approved, I saw this on clean ubuntu install

**Comment by bigbn** [comment]
The reason is custom theme. With adwaita there is no any borders even in ubuntu.

**Comment by amankhoza** [comment]
> The reason is custom theme. With adwaita there is no any borders even in ubuntu.

If you look carefully even with Adwaita (first image) there is still a trim but it is less apparent, but the exact same problem is present, see the screenshots I have attached. The second screenshot is a custom theme (materia) where the trim is more apparent because of the different opacity level of the background in the custom theme. So the problem appears to be theme independent.

![ddt_adwaita](https://user-images.githubusercontent.com/5832764/66605931-ef19f680-eba8-11e9-887f-9cc4e3238a5b.png)
![ddt_customtheme](https://user-images.githubusercontent.com/5832764/66605938-f3461400-eba8-11e9-8c14-1462b77b9caa.png)

**Comment by amankhoza** [comment]
```
commit 53e0bc97b122b0d810adffb9c358e7caae2989a6
Author: Aman Khosa <amankhoza@hotmail.co.uk>
Date:   Thu Oct 10 23:39:00 2019 +0100

    Tweak padding

diff --git a/drop-down-terminal-x@bigbn.pro/extension.js b/drop-down-terminal-x@bigbn.pro/extension.js
index e909cc0..be6755f 100644
--- a/drop-down-terminal-x@bigbn.pro/extension.js
+++ b/drop-down-terminal-x@bigbn.pro/extension.js
@@ -597,10 +597,10 @@ const DropDownTerminalXExtension = new Lang.Class({
         break
     }
 
-    this._windowX = this._windowX + leftPadding
-    this._windowY = this._windowY + topPadding
-    this._windowWidth = this._windowWidth - leftPadding - rightPadding
-    this._windowHeight = this._windowHeight - topPadding - bottomPadding
+    this._windowX = this._windowX + leftPadding - 1
+    this._windowY = this._windowY + topPadding - 1
+    this._windowWidth = this._windowWidth - leftPadding - rightPadding + 2
+    this._windowHeight = this._windowHeight - topPadding - bottomPadding + 2
 
     // applies the change dynamically if the terminal is already spawn
     if (this._busProxy !== null && this._windowHeight !== null) {
```

This quick hack removes the trim, so the problem is likely near this part of the code.
