### ISSUE TITLE
Toggle on scroll behaviour changed, animations not working

### ISSUE THREAD

**Issue by Phidica** [bigbn/drop-down-terminal-x#37]
Version info: As distributed by Gnome Shell Extensions. Fedora 29. Gnome 3.30.2

The previous toggle-on-scroll behaviour was to only open with scroll down, and only close with scroll up. Since accepting the Gnome Shell Extensions update today, the terminal seems to only respond to scroll down, which is unintuitive when it comes to closing it. Additionally, it seems animation is not working? Whether I tick or untick the box in the settings has no effect.

**Comment by rcdeoliveira** [comment]
Same behavior on Debian Bullseye (gnome-shell 3.30.2)

**Comment by Phidica** [comment]
I think the extension updated a few days ago, and the behaviour has changed. Now it only responds to scroll *up*, only opening or closing with scroll up.

**Comment by bigbn** [comment]
@Phidica this extension is not updated at extensions.gnome.org yet. You can check is it fixed if you manualy install this extension from github.

**Comment by Phidica** [comment]
Ah, yes it has been fixed, as of the latest release to hit extension.gnome.org
