### ISSUE TITLE
How to forcefully kill ther termial drop-down.

### ISSUE THREAD

**Issue by kamleshkarwande** [bigbn/drop-down-terminal-x#39]
Not a bug, but wanted to know how I can overcome this problem.

When connected to a remote server via SSL, sometimes the connection is dropped. In the regular terminal window, I need to close the current tab/window and again create a new SSH connection.

But in "drop-down-terminal-X" how can I forcefully close the terminal window, the host key does not kill the current task it just hides the terminal window.

How to forcefully close the drop-down-terminal-x?

NOTE : exit command restarts the window, but in my case  no input can be given as the ssh command is stuck

**Comment by bigbn** [comment]
You can use tabs. Tabs can be closed (child process must be killed) via middle mouse click or context menu "Close" item.

**Comment by kamleshkarwande** [comment]
That's Great ...
