### ISSUE TITLE
Feature request: scroll while bottom line updates

### ISSUE THREAD

**Issue by rusins** [bigbn/drop-down-terminal-x#40]
In most terminals, you can scroll up and down while a command like `apt upgrade` is running. In drop-down-terminal-x however, every time the percentage bar updates (i.e., the bottom line of the output), the terminal jumps down to the bottom. This is annoying when you want to see what the program outputted earlier, while it's still actively working (printing to standard out).

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/66502470-d203fb80-eab4-11e9-9745-fd684ab6097d.png)

**Comment by rusins** [comment]
Thank you, was unaware the latest version had this feature. Works perfectly! :+1:
