### ISSUE TITLE
Custom fonts ?

### ISSUE THREAD

**Issue by GregoryOrciuch** [bigbn/drop-down-terminal-x#42]
Hi,

I do have an impression that default font I'm using on Fedora 31 for that drop-down-termin-x somewhat sucks and could look nicer.

is there a way to set some different font ? I'd like to use e.g. terminus or source code pro.

**Comment by bigbn** [comment]
This is extension(like gnome-terminal, tilix and etc) uses system monospace font from gnome preferences. You can select any font you want in gnome-tweaks.
