### ISSUE TITLE
vifm in drop-down-terminal-x shows only one column

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [bigbn/drop-down-terminal-x#45]
When running _vifm_ in _drop-down-terminal-x_, only one of two columns are displayed, even after executing the vifm command `:vsplit`. Running _vifm_ in other terminal emulators show two columns as expected.

**Comment by bigbn** [comment]
Which distro?

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/70552762-dfe80280-1b71-11ea-8ed7-40df5ae51955.png)

**Comment by bigbn** [comment]
Ah @TitusLabienus it's you ) Nice to see you, again! I know, you are using archlinux. Me too, and see, there is no problems. Could you, please send screenshot, maybe we will detect something on it.

**Comment by bigbn** [comment]
Due inactivity
