### ISSUE TITLE
Does not overlay when another application (for example firefox) is in fullscreen mode

### ISSUE THREAD

**Issue by shap00r** [bigbn/drop-down-terminal-x#46]
As a drop down terminal it is expected that it always stays on top of other windows and programs even if they are in fullscreen mode.

**Comment by bigbn** [comment]
_Related changes https://github.com/zzrough/gs-extensions-drop-down-terminal/commit/f71b84a83c39a0f6c7feaa95950f0642f04a7d30_

**Comment by bigbn** [comment]
@mahoor Could you please check (by manually installing), what terminal behaviour and look are still the same on your distro?

**Comment by shap00r** [comment]
> @mahoor Could you please check (by manually installing), what terminal behaviour and look are still the same on your distro?

Now it is working fine, staying on top of fullscreen applications. Just for providing informations, I tested on Fedora 31, Gnome 3.34.2 (working correct on both Wayland and Xorg).

**Comment by snaggen** [comment]
It works on wayland in that way that it will default be shown on top even if there is a fullscreen window. However, it will not always stay on top, if you select the fullscreen window that gets on top and the terminal gets hidden behind it.

**Comment by bigbn** [comment]
I'm not sure that extension can change wayland behaviour.

**Comment by snaggen** [comment]
The on screen keyboard that is part of gnome shell does this. So, by using the same widgets it should be possible.
