### ISSUE TITLE
Can't adjust or toggle tabs transparency and multi monitor mode is not working

### ISSUE THREAD

**Issue by belfeldt** [bigbn/drop-down-terminal-x#48]
Edit: Mea maxima culpa! Problem described below only happens with automatically installed version. Manually installed last version 10 works perfectly an has even more features. 
Cheers!
####################
Drop Down Terminal X supporting ssh_config makes it a perfect replacement within Gnome3 for guake or similar.

Two issues:
First: Tabs (not whole shell only the tab) are always totally transparent. Pretty annoying, depending on the background you can hardly recognize anything on tabs out of focus. There isn't any switch to toggle or regulate that.
Based on guakes behaviour, where monitor with mouse cursor grabs focus, I can't figure out how multi monitor mode works. Setting a specific monitor works flawlessly. But after toggling "Multi-Monitor mode" checkbox, last set display gets focus no matter where mouse cursor is placed. Maybe I'm just fixated on guakes behaviour to discover the trick.

Ubuntu 18.04.3 LTS
Gnome 3.28.2

Thanks for your efforts & regards

**Comment by bigbn** [comment]
Why have you closed the issue? Xorg?
