### ISSUE TITLE
Available in https://extensions.gnome.org/extension

### ISSUE THREAD

**Issue by jidckii** [bigbn/drop-down-terminal-x#5]
Hey.
I see in this fork corrected many problems. It is available in
https://extensions.gnome.org/extension?

**Comment by bigbn** [comment]
@jidckii Not yet. I plan to do it, but I wonder how to deal with the fork extension name

**Comment by tom-dalton-fanduel** [comment]
"Drop Down Terminal 2"?!

**Comment by bigbn** [comment]
I much prefer "Drop Down Terminal X". What do you think?

**Comment by tom-dalton-fanduel** [comment]
Sounds fine to me - as long as it works and is easy to install :D

**Comment by tom-dalton-fanduel** [comment]
I also just thought of "Terminal Drop" as a funny name :)

**Comment by bigbn** [comment]
According to this message this fork might be unneccesary
https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/217#issuecomment-423651735

**Comment by jidckii** [comment]
> According to this message this fork might be unneccesary
> [zzrough#217 (comment)](https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/217#issuecomment-423651735)

It's fine !)
Did you send the pull request?

**Comment by bigbn** [comment]
Yes. 2 years ago
https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/150

**Comment by jidckii** [comment]
> Yes. 2 years ago
> [zzrough#150](https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/150)

ahaha
continuous delivery ))

**Comment by bigbn** [comment]
OK, I'll wait for about a week and then start to publish this fork if nothing changes.

**Comment by tom-dalton-fanduel** [comment]
Did this get published in the end?

**Comment by bigbn** [comment]
https://extensions.gnome.org/extension/1509/drop-down-terminal-x/

**Comment by tom-dalton-fanduel** [comment]
:heart:
