### ISSUE TITLE
Sometimes copy doesnt work

### ISSUE THREAD

**Issue by amankhoza** [bigbn/drop-down-terminal-x#55]
Whether you do ctrl+shift+c or select text then right click and copy, sometimes it just doesnt work.

**Comment by amankhoza** [comment]
Update: it appears to only allow pasting in the terminal using the mouse scroll wheel click, the copy doesn't get sent to the global clipboard so isn't available in other applications.

**Comment by luetage** [comment]
Install xclip or similar to enable global clipboard in terminal. At least that's why it's working for me.

**Comment by amankhoza** [comment]
@luetage I do have xclip installed but since I am not able to consistently reproduce this issue I'll close it and reopen if it happens again and I have more details.
