### ISSUE TITLE
Is it possible to lighten the blue in palette? 

### ISSUE THREAD

**Issue by tuberry** [bigbn/drop-down-terminal-x#58]
![tmp](https://user-images.githubusercontent.com/17917040/75703505-929fab00-5cf2-11ea-8b8b-557c87cabfef.png)

**Comment by bigbn** [comment]
zzrough/gs-extensions-drop-down-terminal#57 related

**Comment by bigbn** [comment]
As temporary solution to fix at least `ls` command you can set custom colors for it by dircolors:

    dircolors -p > ~/.dircolors
    sed -i "s/^DIR.*$/DIR 01;36/" ~/.dircolors
    echo 'eval $(dircolors .dircolors)' >> .bashrc

![image](https://user-images.githubusercontent.com/740864/75711727-4e0b1400-5ce0-11ea-8966-38cc3159a9c0.png)

**Comment by bigbn** [comment]
https://gitlab.gnome.org/GNOME/gjs/issues/170 - also related

**Comment by tuberry** [comment]
Thanks, that looks much better.
