### ISSUE TITLE
The terminal doesn't close anymore

### ISSUE THREAD

**Issue by Shaltz** [bigbn/drop-down-terminal-x#62]
With the latest update (march 2020), no matter what I do, I can make the terminal appear but not hide... It worked perfectly fine until it auto updated... :(
my toggle key is ²

I had to disable the extension... 
so sad, this is probably the tool that I use the most...

**Comment by bigbn** [comment]
Which distro?
Which gnome version?
Xorg or Wayland?
What is ²?

`journalctl -a | grep 'terminal-x\|JS-ERROR'`

**Comment by Shaltz** [comment]
Hi 
sorry, I should have given more info...

ubuntu 18.04.4
gnome 3.28.2
using Xorg
² is the key, on a french keyboard, which is above the tab key (I guess it's ~ on US keyboards)

[logs-DropDownTerminalX.log](https://github.com/bigbn/drop-down-terminal-x/files/4381806/logs-DropDownTerminalX.log)


tell me if you need some more insights

**Comment by bigbn** [comment]
I see the reason. Fix will be available soon (1-3 days)

**Comment by Shaltz** [comment]
@bigbn 
You're a star, thanks for your work... this extension is, BY FAR, the tool I use the more often...

**Comment by Shaltz** [comment]
how to get the update ?? Do we have to wait until next month update to get it or is there a faster way ?
thanks in advance

**Comment by bigbn** [comment]
It was already published. When it pass the review it will become available automatically. Usualy review is about 1-7 days

**Comment by Shaltz** [comment]
> It was already published. When it pass the review it will become available automatically. Usualy review is about 1-7 days

cool thanks bigbn, I just have to wait... so weird to go back to the plain old terminal now... :/

**Comment by bigbn** [comment]
You can install latest version from git manually
![image](https://user-images.githubusercontent.com/740864/78003143-470c0b80-7349-11ea-8a60-d70c8ce6723b.png)

**Comment by Shaltz** [comment]
> You can install latest version from git manually
> ![image](https://user-images.githubusercontent.com/740864/78003143-470c0b80-7349-11ea-8a60-d70c8ce6723b.png)

the fix works like a charm, thanks again bigbn ;)
