### ISSUE TITLE
Color schemes/palette

### ISSUE THREAD

**Issue by MostFrabjous** [bigbn/drop-down-terminal-x#65]
I'd like to have the possibility to use another color scheme (or is it called palette?) like gnome-terminal has available.

~Why? Mostly annoying is the dark-blue-on-black. I know this can be changed (dir-colors) bus as I'm using a lot of system I don't own, this isn't an option.~
Will be resolved by #66

**Comment by MostFrabjous** [comment]
If anybody wants to use Solarized colors (misusing the TangoPalette var), change this line in terminal.js:
```
const TangoPalette = [Convenience.parseRgbaColor('#070736364242'), Convenience.parseRgbaColor('#dcdc32322f2f'), Convenience.parseRgbaColor('#858599990000'), Convenience.parseRgbaColor('#b5b589890000'    ), Convenience.parseRgbaColor('#26268b8bd2d2'), Convenience.parseRgbaColor('#d3d336368282'), Convenience.parseRgbaColor('#2a2aa1a19595'), Convenience.parseRgbaColor('#eeeee8e8d5d5'), Convenience.pars    eRgbaColor('#00002b2b3636'), Convenience.parseRgbaColor('#cbcb4b4b1616'), Convenience.parseRgbaColor('#58586e6e7575'), Convenience.parseRgbaColor('#65657b7b8383'), Convenience.parseRgbaColor('#838394    949696'), Convenience.parseRgbaColor('#6c6c7171c4c4'), Convenience.parseRgbaColor('#9393a1a1a1a1'), Convenience.parseRgbaColor('#fdfdf6f6e3e3')];
```
As long as #66 isn't merged, you also have to comment in

`terminal.set_colors(ForegroundColor, BackgroundColor, TangoPalette, TangoPalette.length);`

**Comment by bigbn** [comment]
Where have you get Solarized palette colors? Is there any other palettes available?

**Comment by MostFrabjous** [comment]
The Solarized colors are from gnome-terminal, which provides other palettes too.

https://github.com/GNOME/gnome-terminal/blob/mainline/src/profile-editor.c

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/81054623-30248000-8ed8-11ea-94dd-4587ac75ed48.png)
