### ISSUE TITLE
Where are the preferences stored ??

### ISSUE THREAD

**Issue by Shaltz** [bigbn/drop-down-terminal-x#67]
Hi, 

I moved from 18.04 to 20.04 yesterday and some tiny graphical bugs popped up...
FYI I kept the same /home between 18.04 and 20.04... 
To make sure it was related to the version update, I uninstalled dropdown terminal X and reinstalled it, thinking that all the preferences would be reset to their default values but no...
After reinstalling DDTX, I still have my settings in place (my terminal comes from the right side and takes 50% of the screen) as well as the graphical bugs...

so my question is... where are the preferences stored between install and uninstall of DDTX ? and why are they kept ? should you remove all the extensions related files when the extension is uninstalled from the system ??

Here is a screenshot of the situation, maybe it's not related to the 'old 18.04' settings at all and it's a real bug... The tabs are transparent so unreadable if the background is not totally uniform and dark and the terminal, even tho is supposed to only take 50% of the screen(worked fine on 18.04) takes a bit more... a bit annoying if working with windows stuck to the left, as I do...
not a big deal anyways, just a bit annoying, that's all ;)

![Screenshot-DDTX](https://user-images.githubusercontent.com/10232812/80969757-656a9880-8e1a-11ea-8fb9-87bda85a1b3b.png)

EDIT : The "not at 50% of the screen" issue resolve itself as soon as you set the "auto hide dock" flag to ON in the system settings... 1 down, 1 to go :)

**Comment by bigbn** [comment]
https://wiki.gnome.org/Projects/dconf

![image](https://user-images.githubusercontent.com/740864/80980239-737be180-8e39-11ea-9c9d-673a21618199.png)

You can use dconf-editor to manipulate preferences (reset to defaults and erase too).

**Comment by Shaltz** [comment]
Thks @bigbn  but after resetting the preferences to their default, the problem of invisible/transparent tabs remain... I'll open another ticket
