### ISSUE TITLE
undefined behavior 

### ISSUE THREAD

**Issue by mich2k** [bigbn/drop-down-terminal-x#69]
hello, I am having this bug:
if I open the terminal (the animation is quite strange)  it will place quite bad, but if I click on the desktop the terminal resizes and moves in the right fixed place, according to my display
[after the click](https://i.imgur.com/8k2ihYH.jpg)   ( the right empty space disappeared after restoring all the padding settings to default)
[before the click](https://i.imgur.com/DIBEInH.jpg)

 - Distro: Ubuntu 20.04 LTS
 - Gnome-version 3.36.1
 - Extension-version [e.g. 22]
 - Xorg

dell xps 15 7590 4k

edit: this happens for every "Position" (top, right..)
after a random click the terminal perfectly assets to its place

**Comment by bigbn** [comment]
do you use xrandr?

**Comment by mich2k** [comment]
xrandr is installed, I use it manually to change display brightness

**Comment by TinfoilPancakes** [comment]
+1, when using xrandr for undetected edid w/ multi-monitor I see similar behavior. It starts offset from correct position.
