### ISSUE TITLE
Crashing when using custom colors

### ISSUE THREAD

**Issue by brknkfr** [bigbn/drop-down-terminal-x#74]
**Describe the bug**
Drop Down Terminal X is crashing when custom colors and _not_ the  system colors are enabled.

**To Reproduce**
1. Go to 'Drop Down X Terminal Settings -> Colors' in the settings and disable 'system colors' checkbox.
2. Try to open terminal with keybinding
3. Crash (with a message, that I should enable debug mode)

**Desktop (please complete the following information):**
 - Distro: Gentoo 
 - Gnome-version: 3.34.5
 - Extension-version 16
 - wayland

btw, where do I enable debug mode or how do I debug?

**Comment by bigbn** [comment]
`journalctl -a | grep 'terminal-x\|JS-ERROR'`

**Comment by brknkfr** [comment]
Here we go. Pressing the key combination for displaying the terminal.

```
Mai 13 21:44:33 sumsum gnome-shell[3378]: forking 'gjs /home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js /home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro'
                                  _createTerminalView@/home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js:790:7
                                  _createTerminalTab@/home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js:595:22
                                  addTab@/home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js:503:17
                                  _init@/home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js:265:5
                                  @/home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js:1229:18
Mai 13 21:44:34 sumsum gnome-shell[5079]: Script /home/sl/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/terminal.js threw an exception
```

**Comment by bigbn** [comment]
There are missing the exact reason of exception in this log.  After the last line of provided logs the full exception description is available. Please find it via `journalctl -a` and post here

**Comment by romgrk** [comment]
There's no more info in those logs but running directly `gjs terminal.js` yields:
```
(gjs:1648766): Gjs-WARNING **: 03:58:22.742: JS ERROR: Error: Flat array of type RGBA is not currently supported
_createTerminalView@terminal.js:790:7
```

I'm guessing `VTETerminal.set_colors(fg, bg, palette)` isn't happy with `palette`'s format.

From GJS commit: [5cb34600b13cfdbf101823a8636dc6469103e510](https://gitlab.gnome.org/GNOME/gjs/commit/5cb34600b13cfdbf101823a8636dc6469103e510)
Tracking issue upstream: https://gitlab.gnome.org/GNOME/gjs/issues/44

Meanwhile, if you could make it possible again to set the fg/bg color even if setting the palette doesn't work would be nice.

**Comment by brknkfr** [comment]
Seems to work now, don't know why. I'm now on gnome-shell 3.36.5
