### ISSUE TITLE
open with cutom text/command

### ISSUE THREAD

**Issue by fbmoose48** [bigbn/drop-down-terminal-x#75]
Would be great if it could be customized to display something other than the Month/Year and current release notes on opening. an option to display nothing but the single line prompt would be nice for space saving as well.

Didn't see an obvious way to edit this through the options panel.

**Comment by bigbn** [comment]
You can customize you shell as you vish via prompt and bashrc. 
Update notes are displayed only once per release and dont showing no more  till next update. This message can be easily cleared with CTLR+L for example, there is no need to save some space for command line, it do it by itself.
