### ISSUE TITLE
extention will not launch or display

### ISSUE THREAD

**Issue by sewnie** [bigbn/drop-down-terminal-x#78]
using manjaro
dunno what else to put here 

he settings of extension drop-down-terminal-x@bigbn.pro had an error:
```
Error: Type name DropDownTerminalSettingsWidget is already registered
```

Stack trace:
```
_construct@resource:///org/gnome/gjs/modules/script/_legacy.js:531:31
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
@/home/wael/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/prefsWindow.js:85:38
@/home/wael/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/prefs.js:15:40
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by EvanWashkow** [comment]
Can confirm. Arch Linux.

**Comment by bigbn** [comment]
I have the latest Arch Linux and don't know how to reproduce it

**Comment by EvanWashkow** [comment]
@bigbn The issue seems to have (magically) resolved itself. I had previously uninstalled it, but after installing it again, it appears to now work. It is possible that this was a bug produced in an Arch update.

**Comment by akashksinghal** [comment]
I'm facing a similar issue on Ubuntu 20.04 LTS.

`Error: Type name DropDownTerminalSettingsWidget is already registered
Stack trace:
  _construct@resource:///org/gnome/gjs/modules/script/_legacy.js:531:31
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  @/home/akashksinghal/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/prefsWindow.js:85:38
  @/home/akashksinghal/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/prefs.js:15:40
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17`

**Comment by oskar1992** [comment]
I had this on Manjaro 20.2. Had uninstalled Drop Down Terminal and wanted to install Drop Down Terminal X: this error when clicking on settings. But once I uninstalled Drop Down Terminal X again and rebooted it worked with the next installation..
