### ISSUE TITLE
Can't change tabs shortcuts

### ISSUE THREAD

**Issue by Nunels** [bigbn/drop-down-terminal-x#8]
There is no way to change tabs shortcut. Notebooks touchpads don't have middle-click so would be useful to change this.

**Comment by bigbn** [comment]
You can close tab by standard combination CTRL+D, or via "exit" command, or using context menu.
But I agree, custom combination would be heplfull.

**Comment by amlamarra** [comment]
To add onto this, it would be nice to be able to change the shortcuts to switching to different tabs. For instance, I always set `Ctrl+,` to move to the previous tab & `Ctrl+.` to move to the next tab. This way I don't need to move my hands off the home row in order to switch.

**Comment by ericdallo** [comment]
@bigbn, maybe a option in the extension menu where you can customize the shortcuts, similar to the `activation  shortcut`, where i can specify a custom shortcut for activate the drop down terminal.

**Comment by bigbn** [comment]
![image](https://user-images.githubusercontent.com/740864/59567091-02dda200-907a-11e9-9500-e7a86759fe52.png)
Made in fdab7d959aee38a47c9de7200ee82a85b80ed3e7 d51d1ce3f3b72f4d67881a56881a2d087a9dc912 2f130c1619e0b81982a2aa65c8dbfd253f9270d0 02ec2cc0d0f6a11997d718aeddfb271563df0b7b, released in 02ec2cc0d0f6a11997d718aeddfb271563df0b7b
But must be tested before releasing to a new version

**Comment by thedrint** [comment]
> There is no way to change tabs shortcut. Notebooks touchpads don't have middle-click so would be useful to change this.

Try to left click + right click with touchpad buttons on tab caption - on my laptop it closes tab.
But i agree, it would be great to have customized shortcuts.

**Comment by bigbn** [comment]
The middle click behaviour will still work
