### ISSUE TITLE
Terminal stopped working - missing JS module 'tweener'

### ISSUE THREAD

**Issue by jmayday** [bigbn/drop-down-terminal-x#84]
Terminal stopped working after recent system update

**To Reproduce**
1. Try pressing shortcut to show terminal - nothing happens

**Expected behavior**
Terminal appears

**Desktop (please complete the following information):**
 - Distro: Arch Linux
 - Gnome-version 3.38.1
 - Extension-version 16
 - X11

**Additional context**
Extensions window shows this error next to Dropdown Terminal X: _No JS module 'tweener' found in search path_

**Error logs**
```
paź 13 09:31:59 mayday gnome-shell[1174]: JS ERROR: Extension drop-down-terminal-x@bigbn.pro: ImportError: No JS module 'tweener' found in search path
                                           @/home/kuba/.local/share/gnome-shell/extensions/drop-down-terminal-x@bigbn.pro/extension.js:48:17
```

**Comment by bigbn** [comment]
You should wait until new version will be available on extensions.gnome.org or manually install the latest version from repo. Read readme to knew how to do it.

**Comment by jmayday** [comment]
> You should wait until new version will be available on extensions.gnome.org or manually install the latest version from repo. Read readme to knew how to do it.

Sorry, I didn't try that at first place. After installing manually it works perfectly fine again. Thanks!
